### ISSUE TITLE
Single spot ALEX

### ISSUE THREAD

**Issue by kfriedl** [tritemio/niconverter#1]
Hello Antonino,
Is niconverter also applicable to single spot measurements? I have the timestamps arrays stored in earrays in hdf5 files, already rollover corrected. But merging and sorting big arrays (~GB) in RAM gets a problem. How do you do the sorting in niconvert, I could not completely understand where you apply the chunks. Edit: What does the _read_chunk method do? Sorry if the case seems silly, I'd really appreciate the help!
Best whishes,
Karoline

**Comment by tritemio** [comment]
Hi Karoline,

can I ask to move the discussion to the phconvert repos? I opened a [new issue there](https://github.com/Photon-HDF5/phconvert/issues/24). 

Thanks.
